<div class="container">

  <header>

  </header>

  <div class="cover">
    <h1>Discover what's out there.</h1>
    <form  class="flex-form">
      <label for="from">
        <i class="ion-location"></i>
      </label>
      <input type="search" placeholder="Where do you want to go?">
      <input type="submit" value="Search">
    </form>
    <div id="madeby">
      <span>
        Photo by <a href="https://btchubzm.online" target="_blank">BTCHUB</a>
      </span>
    </div>
  </div>

</div>
